include $(SRC_RT)/myOS/kernel/task/task_sche/Makefile
TASK_OBJS= 	output/myOS/kernel/task/task.o \
			output/myOS/kernel/task/task_arr.o \
			output/myOS/kernel/task/task_sched.o \
			output/myOS/kernel/task/taskPara.o \
			${SCHED_OBJS}